---
title: "Spam filter"
subtitle: "Week1-ex1, solution"
output: pdf_document
---


This exercise, with many alternative stories and numerical values, is a classical 
example of the importance of prior information and of taking into account the 
baseline prevalence. 

Erik knows that 65\% of his emails are spam. Spam filter classifies 75\% of spam to be spam. Furthermore, filter classifies 6\% of emails as spam even if they are not spam. What is the probability that an email classified as spam is not spam? 

## Answer

prior: $p(spam=1)=0.65$

likelihood: $p(test=1|spam=1)=0.75$ and $p(test=1|spam=0)=0.06$ 

posterior probability that an email classified as spam is actually spam is:
\begin{align*}
p(spam=1|test=1) &= \frac{p(test=1|spam=1)p(spam=1)}{p(test=1|spam=1)p(spam=1)+p(test=1|spam=0)p(spam=0)} \\
&= \frac{0.75\times 0.65}{0.75\times 0.65 + 0.06\times 0.35}\\
\end{align*}

Hence, the final answer is 

$p(spam=0|test=1)=1-p(spam=1|test=1)$

```{r}
1-(0.75* 0.65)/(0.75* 0.65 + 0.06* 0.35)
```
## Grading

**Total 10 points:** 3 points if prior and likelihood have been defined correctly. Extra 4 points if the Bayes Theorem has been formed correctly. Extra 3 points (total 10) if the result is correct.